spring.application.name=projeto-tcc
# ===============================
# DATASOURCE
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/projeto_tcc}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=${JWT_SECRET:umaChaveSuperSecretaDeNoMinimo32Caracteres123456}
# ===============================
# LOGGING
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

curriculos.upload-dir=${CURRICULOS_UPLOAD_DIR:C:/curriculos}
openai.model=gpt-3.5-turbo
openai.api.url=https://api.openai.com/v1/chat/completions
openai.api.key=${OPENAI_API_KEY:}
huggingface.api.key=${HUGGINGFACE_API_KEY:}

# ===============================
# ACTUATOR / PROMETHEUS
# ===============================
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=never
management.prometheus.metrics.export.enabled=true
